def program8():
    print()       
    print("-----------------------------------------------------------------------------------------------------------")
    print("                                         MONTHLY HIGHLIGHT REPORT")
    print("-----------------------------------------------------------------------------------------------------------")
    print("                                          HAB TAXI SERVICE")
    print("                                          442 MONTREAL ST")
    print("                                        ST. JOHN'S NL, A1A1A1")
    print("                                           (709) 907-7979")
    print("-----------------------------------------------------------------------------------------------------------")
    print(f"                            MONTHLY HIGHLIGHTS FROM [DATE ONE] - [DATE TWO]")
    print()
    print("   HIGHLIGHT SUMMARY:")
    print("-----------------------------------------------------------------------------------------------------------")
    print("   RENTAL NUMBERS:")
    print()
    print(f"  HIGHEST VOLUME DAY:     [DAY THIS MONTH WITH THE MOST RENTALS]")       
    print(f"  LOWEST VOLUME DAY:      [DAY THIS MONTH WITH THE LEAST RENTALS]") 
    print()
    print("-----------------------------------------------------------------------------------------------------------")
    print("   EXPENSED ITEMS:")
    print()
    print(f"  MOST EXPENSED ITEM:     [ITEM THAT WAS EXPENSED ON INVOICES THE MOST THIS MONTH]")
    print(f"  LEAST EXPENSED ITEM:    [ITEM THAT WAS EXPENSED ON INVOICES THE LEAST THIS MONTH]")
    print()
    print("-----------------------------------------------------------------------------------------------------------")
    print("   PROFIT MARGINS:")
    print()
    print(f"  PROFIT MARGIN INCREASE:          [PROFIT MARGIN INCREASE/DECREASE BETWEEN THIS MONTH AND LAST]")
    print()
    print(f"  MOST PROFIT MARGIN INCREASE DAY: [DAY THIS MONTH WITH THE MOST PROFIT MARGIN INCREASE]")
    print(f"  LEAST PROFIT MARGIN INCREASE DAY:[DAY THIS MONTH WITH THE LEAST PROFIT MARGIN INCREASE]")
    print()
    print("-----------------------------------------------------------------------------------------------------------")
    print("   HIGHLIGHT SUMMARY:")
    print()
    print(f"  HIGHEST VOLUME DAY:     [DAY THIS MONTH WITH THE MOST RENTALS]") 
    print(f"  MOST EXPENSED ITEM:     [ITEM THAT WAS EXPENSED ON INVOICES THE MOST THIS MONTH]")
    print(f"  PROFIT MARGIN INCREASE: [PROFIT MARGIN INCREASE/DECREASE BETWEEN THIS MONTH AND LAST]")
    print("-----------------------------------------------------------------------------------------------------------")
    print("                                      * * * * * END OF REPORT * * * * *")
    # All of the brackets (ex. [DATE LIST], [HST LIST], [DATE ONE/TWO], [NET PROFIT], etc, are formatted inputs/calculated values)

#if __name__ == "__main__":
#    program8()
