def program8():
    print()
    print()
    print()
    print(f"-----------------------------------------------------------------------------------------------------------")
    print(f"                                         MONTHLY HIGHLIGHT REPORT")
    print(f"-----------------------------------------------------------------------------------------------------------")
    print(f"                                          HAB TAXI SERVICE")
    print(f"                                          442 MONTREAL ST")
    print(f"                                        ST. JOHN'S NL, A1A1A1")
    print(f"                                           (709) 907-7979")
    print(f"-----------------------------------------------------------------------------------------------------------")
    print(f"                            MONTHLY HIGHLIGHTS FROM [DATE ONE] - [DATE TWO]")
    print()
    print(f"   HIGHLIGHT SUMMARY:                                                                                      ")
    print(f"-----------------------------------------------------------------------------------------------------------")
    print(f"   RENTAL NUMBERS:                                                                                         ")
    print()
    print(f"  HIGHEST VOLUME DAY:                                                [DAY THIS MONTH WITH THE MOST RENTALS]")       
    print(f"  LOWEST VOLUME DAY:                                                [DAY THIS MONTH WITH THE LEAST RENTALS]") 
    print()
    print(f"-----------------------------------------------------------------------------------------------------------")
    print(f"   EXPENSED ITEMS:")
    print()
    print(f"  MOST EXPENSED ITEM:                              [ITEM THAT WAS EXPENSED ON INVOICES THE MOST THIS MONTH]")
    print(f"  LEAST EXPENSED ITEM:                            [ITEM THAT WAS EXPENSED ON INVOICES THE LEAST THIS MONTH]")
    print()
    print(f"-----------------------------------------------------------------------------------------------------------")
    print(f"   PROFIT MARGINS:                                                                                         ")
    print()
    print(f"  PROFIT MARGIN INCREASE:                     [PROFIT MARGIN INCREASE/DECREASE BETWEEN THIS MONTH AND LAST]")
    print()
    print(f"  MOST PROFIT MARGIN INCREASE DAY:                    [DAY THIS MONTH WITH THE MOST PROFIT MARGIN INCREASE]")
    print(f"  LEAST PROFIT MARGIN INCREASE DAY:                  [DAY THIS MONTH WITH THE LEAST PROFIT MARGIN INCREASE]")
    print()
    print(f"-----------------------------------------------------------------------------------------------------------")
    print(f"   HIGHLIGHT SUMMARY:                                                                                      ")
    print()
    print(f"  HIGHEST VOLUME DAY:                                                [DAY THIS MONTH WITH THE MOST RENTALS]") 
    print(f"  MOST EXPENSED ITEM:                              [ITEM THAT WAS EXPENSED ON INVOICES THE MOST THIS MONTH]")
    print(f"  PROFIT MARGIN INCREASE:                     [PROFIT MARGIN INCREASE/DECREASE BETWEEN THIS MONTH AND LAST]")
    print(f"-----------------------------------------------------------------------------------------------------------")
    print(f"                                      * * * * * END OF REPORT * * * * *")
    # All of the brackets (ex. [DATE LIST], [HST LIST], [DATE ONE/TWO], [NET PROFIT], etc, are formatted inputs/calculated values)